koki-takishita/home-care-navi-front

- assets/variables.scss
- layouts/application.vue
- nuxt.config.js
- pages/users/new.vue
- pages/users/send.vue
ヘッダーから現在作られているページに画面遷移するようにしました。
- ログインボタン→ログイン画面
- 新規登録ボタン→新規登録画面
- ホームケアナビアイコン画像→トップ画面
> ヘッダーから各ページに画面遷移させる

- components/ErrorMsg.vue
- layouts/application.vue
- nuxt.config.js
- pages/users/new.vue
- plugins/axios.js
- store/catchErrorMsg.js
[link](https://dev.classmethod.jp/articles/pull-request-template/)
1. plugins/axios.jsファイル追加
2. 1のファイル内にレスポンスのエラーをキャッチできるプログラム追加
3. 1のプログラムを読み込めるようにnuxt.config.jsに設定
4. store/catchErrorMsg.jsファイル追加
5. vuexで値を管理できるようにした
- このプルリクで何をしたのか？
新規登録時にAPIにリクエストを送った際に、エラーメッセージを受け取れるようにした.
画面に表示はまだしていないこれからやる。あくまで今回はメッセージを受け取り受け取る箱を用意した
- このプルリクでやらないことは何か？（あれば。無いなら「無し」で OK）（やらない場合は、いつやるのかを明記する。）
- どのような動作確認を行ったのか？　結果はどうか？
下記のようにわざとエラーが返ってくるような値をセット  
今回でいうとemailをダブらせる
```
すでにかぶっているメールアドレスでリクエストを送る
※もしかぶってなかったら、適宜追加してください
email: foobar@example.com
```
[![Image from Gyazo](https://i.gyazo.com/4572cd0b4b08f3d7cff4d60c094d325b.png)](https://gyazo.com/4572cd0b4b08f3d7cff4d60c094d325b)
下記のようにコンソール上に422エラーとログが表示されていること(メールアドレスがすでに存在しています)
[![Image from …
> Feature/display エラーメッセージを受け取る 422エラー

- pages/users/new.vue
1. バリテーションルール追加
```ruby
name: 空
email: フォーマット 空
password: 空 全角チェック(type属性をpasswordにすると全角で入力しても半角になる)
password_confirmation: 空 全角チェック 一致のチェック 長さチェック
電話番号: フォーマットチェック
郵便番号: フォーマットチェック
住所: から
```
2. バリテーションが通らないと、ボタンをクリックできないように(不要なリクエストを無効にできる)
リクエストを送る前に正しいフォーマットかチェックできる
- どのような動作確認を行ったのか？　結果はどうか？
https://github.com/koki-takishita/home-care-navi-front/pull/43
前回と同じ動作になるかチェックをお願いしマス
電話番号・郵便番号少し甘くしてます
これ詰めると、かなり大変で正しいものを調査して落とし込む作業でスプリント終わってしまいそうなので、桁数だけチェックする感じで考えています.
```ruby
111-1111-1111
```
> fix: フォームバリテーション修正 リファタリンgぬ

- pages/offices/_id.vue
- http://localhost:8000/offices/1
- 事業所の営業日・休業日を◯✕判定し表示させる
営業日は◯、休業日なら✕
- なし
- 各事業所の営業日・休業日が確認できる
- なし
- https://github.com/koki-takishita/home-care-navi-api/pull/36 の手順を実行する
- API側で`rails db:seed`で事業所のデータを生成する
- Postmanで事業所の休業日を確認する（画像だと日曜と水曜が休み）
https://www.postman.com/
`http://localhost:3000/api/offices/1`
- フロントで事業所詳細画面にアクセスし、反映されてるか確認
http://localhost:8000/offices/1
> build: 営業日・休業日マルバツ判定

- layouts/application.vue
- pages/users/login.vue
- pages/users/new.vue
- plugins/axios.js
1. ログインフォームバリテーション
2. 500エラー対応
スタイリング
バリテーションを突破しないと、ボタンが押せない
サーバー側のエラーを表示できる、つまりマイグレーションエラーが起きててもフロント側で検知できる
なし
- fetch
```ruby
$ git fetch
```
- checkout
```ruby
$ git checkout origin/feature/login-form-validate
```
- fetch
```ruby
$ git fetch
```
- checkout
```ruby
$ git checkout origin/develop
```
- restart
```ruby
$ docker-compose restart
```
手順
1. 下記のURLアクセス
```ruby
http://localhost:8000/users/login
```
2. 空で警告が出る(email・password)
3. フォーマットで警告が出る(email)
- 空で警告
[![Image from Gyazo](https://i.gyazo.com/589cf0838473fbeb55d6a0730fd7e04e.png)](https://gyazo.com/589cf0838473fbeb55d6a0730fd7e04e)
- フォーマット警告
[![Image from Gyazo](https://i.gyazo.com/a8ee5da87ee6b2ab07a2b8a1228c5489.png)](https://gyazo.com/a8ee5da87ee6b2ab07a2b8a1228c5489)
- バリテーション突破したらボタン押せるようになる
[![Image from …
> Feature/login form validate ログインフォームバリテーション

- components/ErrorMsg.vue
- nuxt.config.js
- pages/users/login.vue
1. loginエンドポイント修正
2. logoutエンドポイント修正
```ruby
api/users/sign_in → api/login
api/users/sign_out → api/logout
```
今確認したら、nuxt-linkでもフラッシュ消えないなー、これなんとかします.今週中は無理だけど
ログイン成功後、利用規約とか、プライバシーポリシーにアクセスするとそのまま
追記 閉じるボタン実装しました
追記 前回の「ケアマネージャ」のtypo修正文
API側修正後のエンドポイントに対応
なし
- 前提条件
[このプルリクエストが`develop`にマージされていること or APIはこのブランチで試す](https://github.com/koki-takishita/home-care-navi-api/pull/41)
- 手順
1. ログイン画面からパラメーターセット
2. ログインボタンおす
3. ログイン成功すること確認
```ruby
docker-compose restart
```
[手順動画](https://www.loom.com/share/0d7c6155073848d489af9c9592ef7f34)
> fix: エンドポイント修正

- components/ChooseAreaCard.vue
- components/ChooseCityCard.vue
- components/ChoosePrefectureCard.vue
- components/ErrorMsg.vue
- components/SubTitle.vue
- nuxt.config.js
- pages/top.vue
- plugins/apiToRequestOfAddress.js
- store/areaData.js
- 言葉定義
**ロード: 初回アクセス、ページ遷移**
**リロード: ロードしたあとページを`再読込`する**
- 画面URL
```ruby
http://localhost:8000/top
```
[![Image from Gyazo](https://i.gyazo.com/c54d62f4992848deb2f5d1721ca6e024.png)](https://gyazo.com/c54d62f4992848deb2f5d1721ca6e024)
[![Image from Gyazo](https://i.gyazo.com/03bf0e4451cfd0c27644ca8b39a2eccf.gif)](https://gyazo.com/03bf0e4451cfd0c27644ca8b39a2eccf)
[![Image from Gyazo](https://i.gyazo.com/42297ece6d0cdcf8186fd50d4fef61f6.gif)](https://gyazo.com/42297ece6d0cdcf8186fd50d4fef61f6)
1. スタイリング
1. 事業所を探す際に、エリアを画面から選択できるようになる
なし
**APIはfetchしなくて良い**
- fetch
```ruby
$ git fetch
```
- checkout
```ruby
$ git checkout origin/feature/topPage
```
1. `やったこと`の`1〜3`の手順と同じ動作になること
2. 適当にエリア、都道府県選択
3. リロードする
4. 下記のように選択した内容はリセットされ、関東、東京でセットされたものが表示される
[![Image from …
> build: create top page layout

- pages/contacts/new.vue
-  問い合わせ入力フォームのレイアウト修正
（名前やメールアドレスのサイズ感などは新規登録ページと合わせました）
-レスポンシブ対応
- バリデーション設定　
- 確認ページで入力項目の情報が表示される機能
- 問い合わせの内容が正しく設定できる
- スマホでもページ崩れずに見れる
-入力不備がある状態での問い合わせ送信ができなくなる
・ローカル上の問い合わせページで確認
http://localhost:8000/contacts/new
参照；
https://gyazo.com/549dc7adef44d576e540cbf98f42a22b
・XD画面と比較
https://xd.adobe.com/view/fbf6c289-81b2-4a4c-80fe-12a68930cc3b-aea5/screen/27f935f4-cd8f-4787-89f5-29a7d0799ee1/
・レスポンシブ対応
・レイアウトの確認
・空だとエラー文が表示される
・バリデーション条件ごとにエラー文が表示される
・入力項目を満たさないと確認ボタンが押せない
- XDと違うところアリ　（分かりやすさと見やすさで変更しました）
・名前フォームのサイズ
・利用者区分フォームの種類とサイズ
・利用者区分のラベルの文章（ユーザー ⇨ 選択してください）
> fix: フォーム修正とバリデーション

- pages/contacts/new.vue
- レイアウト修正
▼XD基準でレイアウトを再度修正しました。
・名前フォーム
・利用者区分フォーム
・お問い合わせ内容テキストエリア
- コード追加
▼V-modelの設定が不足していたので追加記述
・利用者区分
・お問い合わせ内容
・ローカル上の問い合わせページで確認
http://localhost:8000/contacts/new
参照；
https://gyazo.com/614c79694f1bb6eac720d9536244279d
・XD画面と比較
https://xd.adobe.com/view/fbf6c289-81b2-4a4c-80fe-12a68930cc3b-aea5/screen/27f935f4-cd8f-4787-89f5-29a7d0799ee1/
> fix:入力フォーム修正済み

- components/ChooseAreaCard.vue
- components/ChooseCityCard.vue
- components/ChoosePrefectureCard.vue
- components/SubTitle.vue
- pages/top.vue
1. 市町村カード複数対応
2. 全体スタイリング
1. スマホ対応
2. 機能に直接関係ない細かいスタイリング 下記に示す(後回しにする理由は時間がかかるから、issueに書いて後日余裕があれば対応します)
**下に上げたやつで優先度高そうだったら対応します**
- 三角形
- クリック後のアクティブになるやつ
- チェックボックスの色・大きさ(XDとくらべ小さい・色も若干違う)
- チェックボックスはラベルを設定していないため、チェックボックスを直接クリックしないとチェックされない(例えば千代田区をクリックしてもチェックがされない)
1. 住所を複数選択できる
なし
- fetch
```ruby
$ git fetch
```
- checkout
```ruby
$ git checkout origin/feature/topPage
```
[![Image from Gyazo](https://i.gyazo.com/716fc1766888bacc4e766d7d7019854a.gif)](https://gyazo.com/716fc1766888bacc4e766d7d7019854a)
[![Image from Gyazo](https://i.gyazo.com/cd68ba9963070a3154ea9f8d91813130.gif)](https://gyazo.com/cd68ba9963070a3154ea9f8d91813130)
[![Image from Gyazo](https://i.gyazo.com/7b5ce76fe423a38b9ab03c7c0dbfe3f3.gif)](https://gyazo.com/7b5ce76fe423a38b9ab03c7c0dbfe3f3)
- …
> 市町村カード複数対応・スタイル調整

- layouts/application_specialists.vue
- pages/specialists/login.vue
- pages/specialists/users/new.vue
- pages/users/login.vue
- plugins/login.js
[link](https://dev.classmethod.jp/articles/pull-request-template/)
- https://example.com
- ケアマネージャーのログイン画面のレイアウトとページ遷移先の設定
- ログイン権限の設定（現状：ユーザーもケアマネのログイン画面からログインできてしまう）
- ログイン後のヘッダーの設定
- エンドポイントの設定（現状：カスタマーと同じエンドポイントになっている）
- ケアマネージャーのログイン画面からログインできる
- ログイン後のページ遷移（仮でケアマネの新規登録画面に遷移するようになってます）
- なし
ブランチ操作
```
git fetch
```
```
git checkout remotes/origin/feature/specialists_session
``` 
手順
```
1.yarn dev をしてサーバー立ち上げ
2.http://localhost:8000/specialists/loginにアクセス
3.ログインできるユーザーの値の入力（各自認証済みのユーザーのメアドとパスワード）
4.ケアマネの新規登録画面に遷移する
```
手順動画
https://www.loom.com/share/0f12b9f66d6e4b6dbe847c4742dc0a8b
- カスタマーのパスの設定や、リンクの文言などの修正もしてます
> ケアマネージャーログイン画面レイアウト

- pages/specialists/office/_id/staffs/index.vue
- pages/specialists/office/_id/staffs/new.vue
- スタッフ一覧画面作成
- PC・SPレイアウト
- スタッフ一覧取得
- 画像がないスタッフは人型アイコン表示
- 名前とふりがなは１行、紹介文は２行まで表示させ、それ以降は「...」と表記して隠す（スタイル崩れ防止のため）
- スタッフ一覧画面⇔スタッフ登録画面間の遷移
- 編集・削除ボタンの実装（次スプリント対応）
- 事業所IDごとのスタッフの絞り込み（次スプリント以降対応）
- スタッフの一覧が見れる
- なし
- API側　fetch後、checkout
```
git fetch
```
```
git checkout feature/スタッフseed
```
- APIでfetchとcheckoutが終わったら、ダミーデータを作成する必要があります。まずは、APIのプルリクの動作確認の手順を行ってください
[https://github.com/koki-takishita/home-care-navi-api/pull/47](https://github.com/koki-takishita/home-care-navi-api/pull/47)
- fetch後、checkout
```
git fetch
```
```
git checkout origin feature/スタッフ一覧画面作成
```
- こちらのloomの動画をご覧ください。レイアウトの確認と、登録画面に遷移して実際にスタッフ登録を行ってください。
[loom スタッフ一覧画面](https://www.loom.com/share/4951c3a106d043f69a0f47fbc1894a95)
[PC-スタッフ一覧画面](https://xd.adobe.com/view/fbf6c289-81b2-4a4c-80fe-12a68930cc3b-aea5/screen …
> build: スタッフ一覧画面作成

- components/ChooseAreaCard.vue
- components/ChooseCityCard.vue
- components/ChoosePrefectureCard.vue
- components/SubTitle.vue
- layouts/application.vue
- pages/contacts/confirm.vue
- pages/top.vue
- store/areaData.js
1. TOP画面、サブタイトル・エリアカードスマホ対応
1. 県・市町村カードスマホ対応
- 現在エリアカードスマホサイズ時に、エリアをクリックすると何も表示されなくなる挙動になっている(正常)
- 次のプルリクで、クリックした時に県・市町村のカードを表示する実装にする予定
2. 画面切り替え時に一瞬スタイルが崩れる(調査中)
試したけどだめだったやつ
- v-clock
- mounted
1. TOP画面の一部だが、スマホサイズに対応した
スマホサイズでは、県カードまでたどり着けない
[![Image from Gyazo](https://i.gyazo.com/4a984dc3ea17e270a99f4d5dbcad7100.gif)](https://gyazo.com/4a984dc3ea17e270a99f4d5dbcad7100)
frontのみ
```ruby
git fetch && git ch origin/feature/build-top-page-responsive
```
[画面図](https://xd.adobe.com/view/fbf6c289-81b2-4a4c-80fe-12a68930cc3b-aea5/specs/)
1. 幅によって、サブコンポーネントとエリアカードがスマホのレイアウトになっていることを確認
[![Image from Gyazo](https://i.gyazo.com/f5a4af9d7cf993bffbbdc3d8ac8a5819.gif)](https://gyazo.com/f5a4af9d7cf993bffbbdc3d8ac8a5819)
アイコンは、こちらで用意したもの使ってます。わけは下記のとおりです。
[![Image from …
> トップ画面一部レスポンシブ対応 SubComponent AreaCard

- pages/contacts/confirm.vue
- pages/specialists/office/_office_id/staffs/_staff_id/edit.vue
- pages/specialists/office/_office_id/staffs/index.vue
- pages/specialists/office/_office_id/staffs/new.vue
- plugins/logout.js
- このプルリクで何をしたのか？
1. スタッフ編集画面作成
2. 編集画面に遷移するときにスタッフの詳細データ表示
3. スタッフ登録・編集時にフラッシュメッセージ表示
4. スタッフ削除ボタン実装（モーダル表示）
- なし
1. スタッフの編集・削除ができるようになる
- なし
- **削除機能を追加しました**
```ruby
git fetch && git checkout origin/feature/staff-destroy
```
APIの動作確認を終わらせる
https://github.com/koki-takishita/home-care-navi-api/pull/53
```ruby
git fetch && git checkout origin/feature/staff-edit
```
- スタッフ一覧画面から、編集ボタンをクリックし、編集する。
http://localhost:8000/specialists/office/1/staffs
- 動画更新しました。編集画面でデータが表示されているのと、フラッシュメッセージの表示の確認をお願いします。
- 削除機能実装しました。編集と削除で動画を2つに分けています。
[スタッフ編集　手順動画](https://www.loom.com/share/a919b4d26c2f40a3bab42d33424315dd)
[スタッフ削除　手順動画](https://www.loom.com/share/97cf4cd874a84653a727c1edbb3dd3b8)
- スタッフ一覧画面でfetchを使っているのですが、fetchの場合`nuxt.config.js`で定義した`baseURL`が使えないので …
> スタッフ編集・削除機能実装

- components/ChooseAreaCard.vue
- components/ChooseCityCard.vue
- components/ChoosePrefectureCard.vue
- components/SubTitle.vue
- store/areaData.js
1. エリアカードスマホ対応
2. 県カードスマホ対応
3. 市カードスマホ対応
1. 背景の色が異なるが、このタスクではやらない
2. 検索窓に入力して、縮めると消える
- PC→スマホ  スマホ→PC
- 必須なら、検索窓実装の時に対応する
[![Image from Gyazo](https://i.gyazo.com/c6cc5f46ea7880831e65e7d25308bc3b.gif)](https://gyazo.com/c6cc5f46ea7880831e65e7d25308bc3b)
3. 一瞬処理が見えてしまうやつ、今の所試して効果なかったやつ 参考サイトあれば教えてほしい
- clock
- mounted
1. スマホからエリアを選択できる
2. 幅を変えても、選択した内容が保持されている.
なし
[画面図](https://xd.adobe.com/view/fbf6c289-81b2-4a4c-80fe-12a68930cc3b-aea5/specs/)
```ruby
git fetch && git checkout origin/feature/top-page-responsiv-prefeture-card
```
```ruby
yarn build
```
```ruby
yarn dev
```
[![Image from Gyazo](https://i.gyazo.com/dfd1b954de4b6faf6631f30b8bfb4023.gif)](https://gyazo.com/dfd1b954de4b6faf6631f30b8bfb4023)
[![Image from Gyazo](https://i.gyazo.com/aa7ae2fc2bf70cdbff5e1fede03fdeea.gif)](https:// …
> エリア・県・市カード

- pages/specialists/office/new.vue
- このプルリクで何をしたのか？
1. スタッフ登録画面レイアウト完成
2. 入力フォームのバリデーション
- 送信処理（次スプリント）
- 休業日のバリデーション（次スプリント）
- なし
- なし
- サーバー起動後、事業所登録画面にアクセス
```
yarn dev
```
http://localhost:8000/specialists/office/new
- レイアウトやバリデーションについて確認（テスト仕様書参照）
```ruby
git fetch && git checkout origin/feature/office_new
```
- office/new.vueのコンソールログをコメントアウトすれば、休業日を選択して送信したときにflagsの値が変わる
```
// console.log(this.flags)
```
> 事業所登録画面レイアウト完成

- layouts/application_specialists.vue
- pages/specialists/login.vue
- pages/users/login.vue
- plugins/login.js
*ログイン時のエンドポイントの統一
* 特になし
* エンドポイントを統一することによってフロントでログインの有無を判定できるメソッドが使用でき、レイアウトの表示の切り替えができるようになる
* 以前のケアマネージャーのログインのエンドポイントが使えなくなります
```ruby
git fetch && git checkout origin/feature/specialists_session
```
```ruby
git fetch && git checkout origin/feature/specialists_login
```
手順1.`http://localhost:8000/users/login`に移動
「カスタマーがログインできる」
手順2.user_typeがcustomerのemailとパスワードを入力
手順3.カスタマーのTOP画面に遷移する
[手順動画](https://www.loom.com/share/f703b55cae3d417aae6f844735880bc2)
「ケアマネージャーはログインできない」
手順2.user_typeがspecialistのemailとパスワードを入力
手順3.エラーメッセージが表示される
[手順動画](https://www.loom.com/share/9958a04b223c45b1aa36bdaebe4f6805)
手順1.`http://localhost:8000/specialists/login`に移動
「ケアマネージャーがログインできる」
手順2.user_typeがspecialistのemailとパスワードを入力
手順3.ケアマネの新規登録画面に遷移する
[手順動画](https://www.loom.com/share/311aa3d74baa42daad1eb675352a …
> ログイン機能（エンドポイント統一)

- pages/offices/_id/appointments/confirm.vue
- pages/offices/_id/appointments/index.vue
- pages/offices/_id/index.vue
- WEB予約画面作成（ログインしてないとアクセスできない）
- 「確認へ進む」ボタンを押したときに、ローカルストレージに入力フォームの値を保存
- ローカルストレージに保存したときに有効期限を設定（3分）
- WEB予約確認画面を作成（ログインしてないとアクセスできない）
- 事業所詳細画面の「WEB予約するボタン」からWEB予約画面に遷移
- 面談希望日時に曜日をつけること（要相談）
- 確認画面で「予約する」ボタンの実装（今日か明日実装予定）
- 事業所詳細画面からWEB予約画面に遷移することができる
- 予約した内容を確認できる
- なし
[画面一覧書 url](https://docs.google.com/spreadsheets/d/1zBUODbQx18IKoKiNmmvuOu6PvCYvTNH5-YTG1JIAcOQ/edit#gid=334611837)
[XD WEB予約画面-PC](https://xd.adobe.com/view/fbf6c289-81b2-4a4c-80fe-12a68930cc3b-aea5/screen/3bf54144-413f-455a-866b-99a1479b8e62)
[XD WEB予約画面-SP](https://xd.adobe.com/view/fbf6c289-81b2-4a4c-80fe-12a68930cc3b-aea5/screen/2c620e5b-f45c-4db9-87eb-c35a5b321931)
[XD WEB予約内容確認画面 PC](https://xd.adobe.com/view/fbf6c289-81b2-4a4c-80fe-12a68930cc3b-aea5/screen/4e5e4e48-7947-4389-b9dd-dc6c857d5b22)
[XD WEB予約内容確認画面 …
> WEB予約画面・確認画面作成

- layouts/application_specialists.vue
- pages/specialists/office/new.vue
- plugins/axios.js
- plugins/logout.js
1.ケアマネージャーログイン後のヘッダーレイアウト
2.ログイン時事業所を持っていれば、事業所編集を表示。持っていなければ、事業所登録を表示
* ヘッダーのリンクの遷移先（各担当の方設定お願いします）
* レイアウトがすっきりしてみやすくなる
* 事業所を登録してないときは登録が表示されて、登録してる時は編集が表示される
* 特になし
```ruby
git fetch && git checkout origin/feature/specialists_login
```
```ruby
git fetch && git checkout origin/feature/specialist-header
```
1,rails db seedを実行
2,ケアマネログインページ `http://localhost:8000/specialists/login`からログイン
```
メールアドレス　specialist@example.com
パスワード　password
```
3.メニューを開き『事業所登録』があることを確認
4.事業所を登録
5.ログアウト
6.再度ログイン
7.メニューを開く
8.事業所を登録したので、メニューを開く事業所編集になっている
[手順動画](https://www.loom.com/share/c850f23300cc4898b17784a729794ed4)
フロントとAPI合わせて確認お願いします
> ログイン後ヘッダーレイアウト

- .github/PULL_REQUEST_TEMPLATE.md
- layouts/application.vue
- layouts/application_specialists.vue
- pages/offices/_id/appointments/confirm.vue
- pages/offices/_id/appointments/index.vue
- pages/offices/_id/appointments/success.vue
- pages/offices/_id/index.vue
- pages/specialists/office/_office_id/care-recipients/new.vue
- pages/specialists/office/_office_id/edit.vue
- pages/specialists/office/_office_id/staffs/index.vue
- pages/specialists/office/new.vue
- WEB予約完了画面実装　登録リクエスト送信
- 事業所詳細画面　コンソールエラー修正
- 事業所詳細画面　事業所画像がないときは**NO IMAGE**画像を表示
- 「WEB予約する」ボタンを押したときに未ログインの場合はアラート表示
- 事業所登録時に編集画面に遷移
- ヘッダーから事業所登録画面・編集画面・スタッフ一覧画面に遷移（URLの事業所IDは、変えても必ずケアマネが持ってる事業所のIDに強制的に遷移します）
- スタッフ登録画面と編集画面で、事業所のIDを変えたときに強制的に事業所のIDのリンクに遷移すること（必要ないと判断したため）
- ヘッダーから事業所登録・編集・スタッフ一覧画面に遷移できる
- ヘッダーからスタッフ一覧画面に遷移後、スタッフ登録・編集・削除ができる
- 事業所登録後に画面遷移し、ケアマネが次の操作をスムーズに行える
- なし
- 上から順に動画を見てください
[事業所登録画面]
**すでに登録済みの場合はRailsのコンソールで削除すること**
http://localhost:8000/specialists/office/new
[事業所登録後、事業所編集画面遷移 ヘッダーからも遷移（PC・スマホ対応）](https://www.loom.com/share/db33f159bb3343dea715f4dce4ba450e)
[事業所登録してないと使えない機能はヘッダーからアクセスできない](https://www.loom.com/share/79b8246016cd4112be4e5f27e2924cc3)
[WEB予約 手順](https://www.loom.com/share/5aa5fbfe55154ab7b3eb28b81efd74a3)
- WEB予約後、APIでデータが登録されているか確認する
```ruby …
```
> WEB予約完了画面　登録リクエスト送信など

- layouts/application.vue
- nuxt.config.js
- pages/appointments/index.vue
- pages/offices/_id/index.vue
- plugins/dateFilter.js
- 予約履歴画面作成
- カードをクリックすると、予約した事業所の詳細ページへ遷移
- 予約履歴がなければ「予約履歴はありません」と表示する
- なし
- ユーザーが予約履歴を見れる
- なし
- こちらのプルリクで動作確認をお願いします
https://github.com/koki-takishita/home-care-navi-api/pull/70
```ruby
git fetch && git checkout origin/feature/appointments_history
```
- 手順動画をご覧ください
[予約履歴画面 手順動画](https://www.loom.com/share/1da59b251ced4f8da661e64c391f8abb)
[画面図](https://docs.google.com/spreadsheets/d/1zBUODbQx18IKoKiNmmvuOu6PvCYvTNH5-YTG1JIAcOQ/edit#gid=334611837)
[XD 予約履歴画面 PC](https://xd.adobe.com/view/fbf6c289-81b2-4a4c-80fe-12a68930cc3b-aea5/screen/7c5bcd66-02a0-41f0-b2d3-657d857752b0/)
[XD 予約履歴画面 SP](https://xd.adobe.com/view/fbf6c289-81b2-4a4c-80fe-12a68930cc3b-aea5/screen/ac3d0418-5ab8-49f9-be8f-8bbdee53e26c)
> build: 予約履歴画面作成

- components/ChooseAreaCard.vue
- pages/top.vue
- このプルリクで何をしたのか？
1. トップページから現在地が取得できるようにした
1. プラグイン化はまだしてない
1. トップページから現在地が取得できる
なし
※ 下記の住所のオフィスが存在していること `rasil db:seed`をすれば入る 都合悪い方は自前で作成お願いします
```ruby
address: 新潟県佐渡市秋津
```
```ruby
git fetch && git checkout origin/feature/search-to-current-area-for-office
```
1. トップページから現在地から探すボタン押す
2. 一覧へ遷移
3. 現在地の住所のオフィスが取得できる
[![Image from Gyazo](https://i.gyazo.com/bb1cc538fc41ce9739b6e89f14d6925a.gif)](https://gyazo.com/bb1cc538fc41ce9739b6e89f14d6925a)
押したあと3秒くらい時間かかります。
> build: topページから現在地を取得できる

- pages/specialists/office/_office_id/care-recipients/_care_recipient_id/edit.vue
- pages/specialists/office/_office_id/care-recipients/new.vue
瀧下さん:編集画面のボタンが『登録する』になっていた　→　『変更する』に修正
渡邊さん：利用者の登録と編集完了時にフラッシュメッセージが一瞬だけ出てますが、すぐ消えてしまうので不要だと思います。 → フラッシュメッセージ表示しない
1不自然な箇所がなくなる
```ruby
git fetch && git checkout origin/develop
```
```ruby
git fetch && git checkout origin/feature/care-recipients_front
```
編集画面（登録後のフラッシュメッセージ、ボタンの確認）[手順動画](https://www.loom.com/share/5ba1474b7ed3431faee8a148854cddd1)
登録画面（登録後のフラッシュメッセージ）[手順動画](https://www.loom.com/share/3430cef76e4d4886aa91f0402bd8b9be)
前回のプルリク　https://github.com/koki-takishita/home-care-navi-front/pull/153
不明点あればおっしゃってください
　
> build: プルリク指摘箇所修正

- components/office/officeCard.vue
[プルリクルール](https://docs.google.com/spreadsheets/d/1XXQGmsRkmIlOpTE6KN6sx6Uya4u_lGKgscMaRdBZDzA/edit#gid=0)
1. 休日の◯ ✕表示が反転していたのでそれの修正
なし
間違った表示の解消
なし
```ruby
git fetch && git checkout origin/bugfix/calendar-logic
```
[トップページに飛びます(localhost:8000/top)](http://localhost:8000/top)
1. オフィス一覧にアクセスする
2. 一覧の◯✕の組み合わせを覚えておく
3. 詳細と組み合わせが一緒なことを確認する
[手順動画](https://www.loom.com/share/1fb42ab1fe314a099a5e9ec573051fc5)
> fix: 休日の表反転していたので修正

- pages/specialists/office/_office_id/appointments.vue
- pages/specialists/office/_office_id/care-recipients/index.vue
- pages/specialists/office/_office_id/staffs/index.vue
- モーダルの実装方法・レイアウトの統一
- スタッフ削除
- 予約の連絡済み・キャンセル済み
- 利用者の削除
- なし
```ruby
git fetch && git checkout origin/feature/unify-the-modal
```
- ケアマネでログイン
```ruby
specialist3@example.com
```
```ruby
password
```
- 機能確認
- 利用者の削除ができるか
- 予約の連絡済み・キャンセル済みができるか
- レイアウト確認
- スタッフ・利用者・予約状況確認でモーダルのレイアウトが統一されているか
> モーダルの実装方法の統一

- jest-puppeteer.config.js
- pages/users/new.vue
- test/e2e/specialists/A_signup_to_login.spec.js
- test/e2e/users/A_signup_to_login.spec.js
1. 新規登録パス修正
2. テストコードapiに合わせる形で一部変更 
- なし
- ルーティング変更して失敗するテストのパッチプログラム テストが突破する
- なし
- api側のセットアップが完了していること
https://github.com/koki-takishita/home-care-navi-api/pull/81
```ruby
git fetch && git checkout origin/fix/change-users-path
```
- テストが成功することを確認する
```ruby
yarn test:e2e
```
> ルーティング変更に伴いテスト修正

- layouts/application_specialists.vue
- pages/specialists/office/_office_id/appointments.vue
- pages/specialists/office/_office_id/care-recipients/_care_recipient_id/edit.vue
- pages/specialists/office/_office_id/care-recipients/index.vue
- pages/specialists/office/_office_id/care-recipients/new.vue
- pages/specialists/office/_office_id/staffs/_staff_id/edit.vue
- pages/specialists/office/_office_id/staffs/index.vue
- pages/specialists/office/_office_id/staffs/new.vue
- test/e2e/specialists/C_create_staffs_update.spec.js
- スタッフ一覧画面と、利用者一覧画面を、更新日順に並べ、ページネーションを実装した
- なし
```ruby
git fetch && git checkout origin/technical/staffs-care_recipients-index-sort
```
```ruby
git fetch && git checkout origin/technical/staffs-care_recipients-index-pagenation
```
- こちらのプルリクの動作確認を終わらせる
https://github.com/koki-takishita/home-care-navi-api/pull/84
- ケアマネでログインする
```ruby
specialist3@example.com
```
```ruby
password
```
- ヘッダーからスタッフ一覧画面に遷移し、ページネーションが動いてるか確認
- 編集したスタッフが先頭に来るか確認
- ヘッダーから利用者一覧画面に遷移し、ページネーションおよびCRUD機能機能の確認
- 編集した利用者が先頭に来るか確認
> スタッフ一覧・利用者一覧画面　ソート＆ページネーション

- components/office/officeDataCardPc.vue
- components/office/officeDataCardSp.vue
- components/office/officeStaffCard.vue
- components/staff/introductionCard.vue
- components/staff/thankCard.vue
- pages/offices/_id/index.vue
1. スタッフ紹介コンポーネント作成
- スタッフ一覧が見れる
- スタッフのお礼一覧が見れる
- お礼が2件以上の場合は開閉ボタンで開閉できる
- スタイリング
- レイアウトはpcのみ
- api側でお礼が多い順に並べる必要あり
- 事業所に在籍しているスタッフ一覧が見れる
- スタッフに寄せられたお礼一覧が見れる
- なし
```ruby
git fetch && git checkout origin/feature/thank-api
```
```ruby
git fetch && git checkout origin/feature/thank-achievement
```
- email
```ruby
kei_sawada@example.net
```
- pass
```ruby
password
```
1. ログインする
2. お礼作成する
3. 2つ以上だったら開閉できる
[手順動画](https://www.loom.com/share/a780ddfdef6e42afa1260e6fbd24955d)
> スタッフ紹介コンポーネント作成

- jest-puppeteer.config.js
- layouts/application.vue
- layouts/application_specialists.vue
- middleware/authenticateCustomer.js
- middleware/authenticateSpecialist.js
- nuxt.config.js
- package.json
- plugins/login.js
- plugins/logout.js
- plugins/persistedstate.js
- store/index.js
- test/e2e/specialists/A_signup_to_login.spec.js
- yarn.lock
- ケアマネ・カスタマー画面のログイン制限
- なし
- カスタマー画面からログインし、ケアマネのURLを直打ちしてもページが表示されずリダイレクトする
- ケアマネ画面からログインし、カスタマーのURLを直打ちしてもページが表示されずリダイレクトする
- なし
```ruby
git fetch && git checkout origin/feature/develop
```
```ruby
git fetch && git checkout origin/fix/login_limit
yarn install
```
手順1.カスタマーでログインする
手順2.ケアマネログイン後の画面のURLを直打ちする
手順3.ケアマネログイン画面に遷移される
[手順動画](https://www.loom.com/share/e6e4d63ad6874199a5c3d617f60f6b69)
（カスタマーも同じ）
なし
> ケアマネ・カスタマー画面ログイン制限

- components/office/officeAreaList.vue
- components/office/officeBookmarkBtn.vue
- components/office/officeCard.vue
- components/office/officeDataCardPc.vue
- components/office/officeDataCardSp.vue
- pages/offices/_id/index.vue
- pages/offices/index.vue
- test/e2e/users/Z_access_footer_link.spec.js
- 事業所一覧画面からブックマーク登録・解除機能
- なし
```ruby
git fetch && git checkout origin/feature/bookmark-create-destroy
```
```ruby
git fetch && git checkout origin/feature/submit-destroy-bookmark
```
- 既存のコードを大きく変更しているので、検索機能や、検索した事業所が取得できるかの確認をお願いします
- 検索した事業所をブックマーク登録・解除する
- ★アイコンの色が変わっていればOK
- ページをリロードする
- ブックマークデータが保持されていればOK
- ブックマークボタンをコンポーネント化し、ブックマークボタンのあるページはコンポーネントを呼び出すだけになり、同じことを毎回書かずに済み、コードがスッキリした
- 関数の実行タイミングを指定秒数遅らせる
- getOfficeメソッド内でpropsの値を取得しているが、propsの読み込みが終わる前に処理が走ってしまいエラーが出てしまうため、指定秒数待ってからメソッドを呼び出すようにしています。この書き方はあまりよくないですが、現状きれいな書き方が見つかっておらず、このような対応を取っています。
`components/office/officeAreaList.vue`
```javascript
mounted() {
setTimeout(this.getOffice, 1000)
},
```
[Vue.jsでsetTimeoutする時の注意点](https://h2r4t.hatenablog.com/entry/2018/05/20/215509)
> 事業所一覧画面からブックマーク登録・解除

- components/office/officeStaffCard.vue
- nuxt.config.js
- pages/offices/_id/thanks/new.vue
1. ログインしないとお礼作成ページへ遷移できないようにalert設定
2. ログインせずに、url直打ちだと強制的にtopページへ遷移
強制リダイレクトの仕様はまだ定かでない
- 直うちの時点で悪質だと判断してフラッシュも何も用意してない
- alertかなにか用意したほうが良いのか
- 悪質なユーザーのブロック
- url直うちでアクセスできなくなる
- ログインしないとお礼作成ページへアクセスできなくなる
```ruby
git fetch && git checkout origin/fix/login-alert-move-thanks-page
```
動作確認用 サンプルユーザー
- email
```ruby
mawatari_ayako@example.net
```
- password
```ruby
password
```
[ログインしていないとアラート出る](https://www.loom.com/share/2a92211b093048ab9c7e9ece8a4aa257)
> お礼をページログインしないと遷移できないように設定

- assets/images/account_icon.svg
- components/staff/introductionCard.vue
- components/staff/thankCard.vue
1. 事業所詳細画面のスタッフ紹介カードにて、スタッフの並び順をお礼の数が多い順に並び替え
2. スタイルの整えた(PC、スマホ対応)
- なし
- fetch and checkout ↓こちらのプルリクも確認
https://github.com/koki-takishita/home-care-navi-api/pull/93
```ruby
git fetch && git checkout origin/feature/staffs-thanks-sort
```
```ruby
git fetch && git checkout origin/feature/staff-introduction-layout
```
- オフィス詳細ページへアクセス
- スタッフの並び順がお礼の数が多い順なことを確認する
※ お礼がない場合は作成する必要あり
[LOOM手順動画](https://www.loom.com/share/401ef65a39e34271b15da3c7c99e69e9)
[画面図](https://xd.adobe.com/view/fbf6c289-81b2-4a4c-80fe-12a68930cc3b-aea5/screen/6907b213-a23b-41ef-aba0-bc451eecbf23/specs/)  
- スタッフの画像が登録されていない場合は↓画像が表示されます。
[![Image from Gyazo](https://i.gyazo.com/cad7876c91b877f9e56cefc134d4defa.png)](https://gyazo.com/cad7876c91b877f9e56cefc134d4defa)
- …
> スタッフ紹介ページ並び替え

- layouts/application.vue
- layouts/application_specialists.vue
- 左上のアイコンクリックすると、今まではurl直うちだったので本番環境だと開発環境に戻ってしまっていたのをrouter.pushに変えたので環境に依存しない画面遷移が可能になる。
- 下記のような形のものは、ルーティングを変えたほうが良い `specialist`と`office`は1:1だから
- 現状
`api/specialist/office/office_id/**/**`
- 変えた形(office_idなしver)
`api/specialist/office/**/**`
- 本番環境でも画面遷移できる 開発には飛ばなくなる
- なし
```ruby
git fetch && git checkout origin/fix/layout-icon-link
```
トップ以外のページからアイコンクリックして、トップ画面へ遷移(カスタマー)
ログイン画面以外からアイコンクリックして、ログイン画面へ遷移(ケアマネ)
ログインしてたら、予約状況に遷移(ケアマネ)
> 左上アイコンをクリックをurl直うちから router.pushで遷移するように設定

- components/office/officeAreaList.vue
- components/office/officeCard.vue
- pages/appointments/index.vue
- pages/offices/index.vue
- plugins/axios.js
- plugins/login.js
- plugins/logout.js
- plugins/persistedstate.js
- store/index.js
- ログイン時に、認証情報をlocalStorageに保存していたものを、保存先をVuexに変更
- Vuexに保存した認証情報の永続化
- リロードしても消えないようにするため。ログアウトをするか、有効期限が切れない限り消えません
- 事業所一覧画面でのAPI通信のタイミングを、asyncDataに戻した
- VuexのStoreに保存されているデータは、サーバーサイドで取得できるため、asyncDataでもHeadersに認証情報をセットできます
- 予約履歴をasyncDataに移行
- ファイル数がちょっと多いですが、見てほしいところはここです
- **plugins/~~**
- **store/index.js**
- 他の機能のasyncDataへの移行（自分が担当していた機能は随時移行しますが、他の人が担当した機能は担当者が対応お願いします。実際に移行する際には**移行ガイド**をご参照ください）
```ruby
git fetch && git checkout origin/technical/mounted-to-asyncdata
```
- ログインをする
- 検証ツールのvueからTimelineの中のVuex Mutationsを選択する
- 最後に発火される`areaData/setCurrentPrefecture`を選択する
- accessToken, uid, expiry, clientの4つが保存されていればOK
- ページをリロードしても消えないか確認
- ログアウトをする
- 最後に発火される`logoutUser`を選択
- 4つの認証情報が空（初期値）になっていればOK
- 事業所の検索機能を一通り確認し、画面の動きなどに不具合がないか確認する
[Vuex の状態を …
> mountedで一瞬だけ見えてはいけないものが見える問題　解決

- components/office/officeCard.vue
- layouts/application.vue
- pages/histories/index.vue
- pages/offices/_id/index.vue
- 閲覧履歴画面実装
- 事業所詳細画面にアクセスしたときに、登録または更新リクエストの送信
- ページ間のレイアウトの統一（ヘッダーとページタイトルのマージンの統一）
```ruby
git fetch && git checkout origin/feature/create-history-index-create-update
```
```ruby
git fetch && git checkout origin/feature/request-create-update-history 
```
1. 事業所を検索して、10件くらい事業所にアクセスする
2. ヘッダーから閲覧履歴画面に遷移する
3. 先頭以外の事業所にアクセスする
4. 2を実施
5. 直近で閲覧した事業所が先頭に来ていればOK
6. 閲覧履歴のないユーザーでログインする
7. 2を実施
8. **閲覧履歴はありません**と表示され、リンクからトップページへ遷移することを確認する
[閲覧履歴 PC版](https://xd.adobe.com/view/fbf6c289-81b2-4a4c-80fe-12a68930cc3b-aea5/screen/fc523e3e-8cbf-4b94-8e51-7e1f2766dcda)  
[閲覧履歴0件 PC版](https://xd.adobe.com/view/fbf6c289-81b2-4a4c-80fe-12a68930cc3b-aea5/screen/0aa771bc-64a8-41e1-b6d5-3d935b3bf497)  
[閲覧履歴 SP版](https://xd.adobe.com/view/fbf6c289-81b2-4a4c-80fe-12a6893 …
> 閲覧履歴画面作成　登録・更新リクエスト送信

- components/thank/cardForOffice.vue
- layouts/application_specialists.vue
- pages/specialists/office/thanks/index.vue
- ケアマネ側お礼一覧ページ作成
- お礼テーブル内の利用者名と年齢を表示
- 削除時に表示させる確認ダイアログ実装
- ケアマネ側のすべての削除機能をモーダルからダイアログへの移行
```ruby
git fetch && git checkout origin/fix/specialist-thanks-list
```
- プルリクはこちら
https://github.com/koki-takishita/home-care-navi-api/pull/117
```ruby
git fetch && git checkout origin/feature/specialist-thanks-list
```
- ヘッダーからお礼一覧にアクセス
- 削除ボタン押す
- キャンセル押す → 削除されない
- OK押す → 削除される
- お礼が1件もない場合は、**お礼投稿履歴はありません**と表示される
[ケアマネ側お礼一覧 PC版](https://xd.adobe.com/view/fbf6c289-81b2-4a4c-80fe-12a68930cc3b-aea5/screen/266cf307-23f2-4742-b3e0-a8fc55fda3fc/)  
[ケアマネ側お礼一覧 SP版](https://xd.adobe.com/view/fbf6c289-81b2-4a4c-80fe-12a68930cc3b-aea5/screen/5aa105df-92b0-4073-a2dc-d227e37846e8/specs/)
なし
> ケアマネ側お礼一覧画面作成　削除機能実装

- components/resetPasswords/edit.vue
- components/resetPasswords/new.vue
- components/resetPasswords/send.vue
- middleware/authenticateCustomer.js
- pages/reset-passwords/edit.vue
- pages/reset-passwords/index.vue
- pages/users/login.vue
- plugins/axios.js
- カスタマー側パスワードリセット機能
1. スタイリング
2. 失敗した時のフラッシュメッセージ 予定(パスワードリセットに失敗しました。もう一度お試しください)
```ruby
git fetch && git checkout origin/feature/reset-password
```
https://github.com/koki-takishita/home-care-navi-api/pull/118
```ruby
git fetch && git checkout origin/feature/reset-password
```
1. ログインページからパスワードリセット申請ページへ遷移
2. メールが送られてくる
3. 新しいパスワードを入力する
4. 成功するとログインページへリダイレクトする
5. 新しいパスワードでログインできる
[手順動画](https://www.loom.com/share/70a94eddfe24472bad9cd6c494db8f47)
6. urlの一部を書き換えると失敗して、パスワード申請画面へ遷移することを確認する
- `access-token`を書き換えてエンター
[わざと失敗させる](https://www.loom.com/share/3ebe6d31e61442de885ebd1aaeb813b1)
[API …
> パスワードリセット機能

- components/resetPasswords/edit.vue
- components/resetPasswords/new.vue
- components/resetPasswords/send.vue
- components/thank/backLink.vue
- pages/reset-passwords/edit.vue
- pages/reset-passwords/index.vue
- パスワードリセット画面のスタイリング
- なし
```ruby
git fetch && git checkout origin/feature/password-rest-form-style
```
- パスワードリセットが問題なく行えるか？
https://github.com/koki-takishita/home-care-navi-front/pull/230
- xdの画面図と大差がないか？
※ パスワードリセット申請画面の文言 パスワードリセットする → 次に進むに変更(amazonのパスワードリセット参考)
[![Image from Gyazo](https://i.gyazo.com/71aa606cda3d21d98a6283e6d6cdb0ad.png)](https://gyazo.com/71aa606cda3d21d98a6283e6d6cdb0ad)
- xdにない画面図に違和感がないか
[sp パスワード申請画面](https://xd.adobe.com/view/fbf6c289-81b2-4a4c-80fe-12a68930cc3b-aea5/screen/93b8d471-dc5d-4d80-a4ca-f3e26491e688/specs/)  
[sp メール送信後画面](https://xd.adobe.com/view/fbf6c289-81b2-4a4c-80fe-12a68930cc3b-aea5/screen/78435fb1-0344-43ea-a044-06a9ec1347b9/specs/)
[pc パスワード申請画面](https://xd.adobe.com/view/fbf6c289-81b2-4a4c-80fe-1 …
> パスワードリセット画面スタイリング

- pages/specialists/office/staffs/_staff_id/edit.vue
- pages/specialists/office/staffs/new.vue
- スタッフ追加・編集画面のバリデーション修正
- 以下のものを入力するとバリデーションがかかる
- 31文字以上の名前
- 31文字以上のふりがな
- 81文字以上の紹介文
- なし
```ruby
git fetch && git checkout origin/fix/staff-validation -> fix/staff-validation
```
- **やったこと**に記載の項目についてテストする
なし
> スタッフ追加・編集のバリデーション修正

- pages/offices/_id/appointments/confirm.vue
- 予約完了時に、ローカルストレージに保存していたフォームデータを削除
- なし
```ruby
git fetch && git checkout origin/fix/appointment-completed-delete-localstorage
```
- 予約完了時に、ローカルストレージの値が消えているか確認
なし
> 予約完了時にローカルストレージ削除

- components/resetPasswords/edit.vue
- components/resetPasswords/new.vue
- components/resetPasswords/send.vue
- middleware/authenticateSpecialist.js
- nuxt.config.js
- pages/reset-passwords/edit.vue
- pages/reset-passwords/index.vue
- pages/specialists/login.vue
- pages/users/login.vue
1. ケアマネ側パスワード設定
2. layoutをqueryによって切り替える
3. 環境変数を参照する設定
- なし
- 使用するブランチ
https://github.com/koki-takishita/home-care-navi-api/pull/123
```ruby
git fetch && git checkout origin/feature/toggle-layout
```
1. .envファイル作成して、redirect_urlを設定する
```ruby
touch .env
PASSWORD_RESET_REDIRECT_URL='http://localhost:8000/reset-passwords/edit'
```
2. カスタマーのパスワードリセットが正常に行える
[loom手順動画](https://www.loom.com/share/327621bcd3e04af3a2434cbb1f2a7761)
3. ケアマネのパスワードリセットが成就に行える
[loom手順動画](https://www.loom.com/share/c404b030a49b4ebcb984c867c40bd6f7)
[API 一覧](https://docs.google.com/spreadsheets/d/1sJ_ZjXjCdBJkpl0gbS_HX3wDeZhihUoqddtIrHCPFnY/edit#gid=0) …
> パスワードリセット ケアマネ側も対応ver

- components/resetPasswords/new.vue
- nuxt.config.js
- package.json
- pages/offices/index.vue
- pages/specialists/users/new.vue
- pages/users/login.vue
- pages/users/new.vue
- yarn.lock
1. axios base urlの設定消えていたので修正
2. ユーザー新規登録 リダイレクト先 環境変数に置き換え
- releasとmainに環境変数の設定(来週のスプリントで、余裕があったら対応)
- 環境変数で置き換えたのはユーザーの新規登録のみ
```ruby
git fetch && git checkout origin/fix/base_url
```
- .envファイル内を下記と同じにする
```ruby
❯ cat .env
PASSWORD_RESET_REDIRECT_URL='http://localhost:8000/reset-passwords/edit'
CUSTOMER_LOGIN_URL='http://localhost:8000/users/login'
END_POINT_BASE_URL='http://localhost:3000/api'
FRONT_TOP_URL='http://localhost:8000'
```
- テストがパスすることを確認する
```ruby
yarn install
yarn test:e2e
```
プルリク説明会で説明したので、今後のタスクは環境変数に対応させてください
[環境変数の設定](https://zenn.dev/kouchanne/articles/83466e36e1c30f174ae8)
> axiosのurlの設定が消えていたので修正・リダイレクト先の設定を環境変数で管理スように設定

- pages/users/new.vue
1. 電話番号ダブリチェックプログラムapiつなぎ合わせ
- ケアマネの方(担当ではないので)
- 他のバリテーションはこのプルリクではやらない
```ruby
git fetch && git checkout origin/technical/phone-number-check-users-sign-up
```
```ruby
git fetch && git checkout origin/technical/users-phone-number-check
```
1. 存在する電話番号であればボタンが押せないことを確認する
- 存在する電話番号取得しとく
```ruby
Office.first.phone_number
User.first.phone_number
```
[loom動画](https://www.loom.com/share/2d5ccaddbbc64d8293857b34cc10e081)
- …
> 入力した電話番号がusersテーブルとofficesテーブルにあればエラーメッセージを表示する

- pages/users/new.vue
- バリテーション修正 文字の長さ
name
email
password
- ケアマネ側
```ruby
git fetch && git checkout origin/technical/validate-to-customer-sign-up
```
1. 新規登録フォームでバリテーションがかかるか確認する
name 30文字超えるとエラー
email 255文字超えるとエラー
password 8文字より小さいエラー
password 32文字超えるとエラー
開発者ツールのコンソールで〇〇文字文用意
```ruby
'a'.repeat(255)
```
- なし
```javascript
NG
```
- …
> カスタマー側新規登録フォームバリテーション修正

- components/thank/new.vue
- pages/thanks/_id/edit.vue
1. お礼関係のバリテーション修正
- なし
```ruby
git fetch && git checkout origin/technical/validate-to-thanks-new
```
1. オフィスページに詳細アクセス(ログイン済み)
2. お礼投稿ページのお礼の内容のとこで、120文字を超えるとエラー出るか確認する
[![Image from Gyazo](https://i.gyazo.com/60aed6474f7bf464c132acf7206ecf13.png)](https://gyazo.com/60aed6474f7bf464c132acf7206ecf13)
3. お礼履歴に遷移
[![Image from Gyazo](https://i.gyazo.com/890e1d53130e1e3d2fe62dfb0b6fa2c9.png)](https://gyazo.com/890e1d53130e1e3d2fe62dfb0b6fa2c9)
4. お礼の編集ページにて、120文字を超えるとエラーが出るか確認する
- 検証ツール 指定した文字数生成
```js
'a'.repeat(120)
```
[ユーザーストーリー](https://docs.google.com/spreadsheets/d/1lORIuXfr7PV5dslAHE4NnRGgNqk0hJ5krfN-tV2YKq8/edit#gid=0) …
> お礼の文字数のバリテーション修正

- pages/offices/_id/index.vue
- store/index.js
- 事業所詳細画面にアクセスしたときに、未ログインでも閲覧データの登録・更新リクエストを送ってしまう不具合修正（「**ログインしてください**」というフラッシュメッセージが出ていた）
- customerがログインしてるかどうかの状態が保存されているstoreの値を参照し、カスタマーでログインしているときだけリクエストを送信するように設定
- なし
```ruby
git fetch && git checkout origin/technical/loggedin-only-request-history-submit-update
```
1. ログインする
2. 事業所詳細画面にアクセスする
3. 閲覧履歴に反映されているか確認
4. 未ログインで2を実施
5. エラーのフラッシュメッセージが出ていないか確認する
- [asyncData で mapGetters を実行するには?](https://stackoverflow.com/questions/58486000/how-to-do-mapgetters-in-asyncdata-nuxt)
```javascript
NG
```
```javascript …
```
> カスタマーでログイン時のみ閲覧データの登録・更新リクエスト

- components/ErrorMsg.vue
- layouts/application.vue
- pages/offices/index.vue
- pages/top.vue
- plugins/axios.js
- store/catchErrorMsg.js
1. 色のバグ修正
2. トランジション
3. 時間で消える
4. レイアウトに影響を与えないように修正
- バグの修正のみで、既存の機能によっては正しく設定しないないと色が白になったりする
```ruby
git fetch && git checkout origin/technical/flash-msg-color
```
1. ログイン・ログアウトを連続で実施して想定通りの色になっているか
※ okそうなら、ケアマネも同じように実装する
[position: absoluteにした要素を中央に寄せる](https://arts-factory.net/position/)
```javascript
NG
```
- …
> カスタマー側 フラッシュメッセージ 色のバグ修正 200→緑 異常系→赤

- pages/specialists/users/new.vue
- 電話番号バリデーション設定
事業所とユーザーで重複している場合は登録できなくなっています
- その他のバリデーション（パスワードやメールアドレスのバリデーションはまだ漏れがあります）
```ruby
git fetch && git checkout origin/fix/specialist_registration
```
1. 存在する電話番号であればボタンが押せないことを確認する
- 存在する電話番号取得しとく
```ruby
Office.first.phone_number
User.first.phone_number
```
[確認動画](https://www.loom.com/share/bc125419e48549a8b11709bbf90a057f)
- #251 
```javascript
NG …
```
> ケアマネ新規登録画面　電話番号バリデーション設定

- components/appointment/officeCard.vue
- pages/appointments/index.vue
- カスタマー側の予約履歴画面の構造を変更
- 予約した回数分だけオフィスのカードを表示
- なし
```ruby
git fetch && git checkout origin/technical/fix-appointments-index
```
```ruby
git fetch && git checkout origin/technical/fix-customer-appointments-index-page
```
- 同じオフィスに2回予約する（ケアマネが持ってるオフィスに予約すること）
- ケアマネ側で2人の予約をキャンセル・連絡済みにする
- カスタマー側で両方反映されていれば 👍 
- なし
```javascript
NG
```
```javascript
- アラート1
ログインをする必要があります
- アラート2
ログインをしてください
- メールを送りました
OK
- メールを送信しました
```
> 予約履歴画面　予約した回数分だけカードの表示

- layouts/application_specialists.vue
1. ケアマネのレイアウトにフラッシュメッセージ組み込み
- なし
```ruby
git fetch && git checkout origin/technical/flash-msg-color-for-sp
```
- ケアマネ画面の方で、ログイン・ログアウトを交互に行って想定通りの動作になっているか?
- こちらのプルリクのケアマネver
https://github.com/koki-takishita/home-care-navi-front/pull/267
- [サイトのタイトル（必須） なければ「なし」と記入](url)
```javascript
NG
```
- [コーディングの命名規則一覧](https://murashun.jp/article/programming/naming-conventions …
> フラッシュメッセージレイアウト組み込み ケアマネ

- pages/offices/index.vue
- オフィス一覧ページ、リロードするとページネーション崩れるバグ修正
- なし
```ruby
git fetch && git checkout origin/technical/office-bug
```
1. nuxt server heroku localで起動
2. オフィス一覧ページへアクセス
3. ページネーションが崩れていなければok
- heroku local
```ruby
yarn build
heroku local
```
- [同じ現象が起こっている人の記事](https://zenn.dev/motoishimotoi/articles/5a6642d8790eaa)
- [client-onlyの公式](https://nuxtjs.org/ja/docs/features/nuxt-components#client-only-%E3%82%B3%E3%83%B3%E3%83%9D%E3%83%BC%E3%83%8D%E3%83%B3%E3%83% …
> fix: リロードしてもレイアウト崩れないように修正

- components/office/officeStaffCard.vue
- components/thank/new.vue
1. オフィス詳細ページ
- スタッフの数が0
[![Image from Gyazo](https://i.gyazo.com/8ac7d133d3aa752aae132b00c3ab79ee.png)](https://gyazo.com/8ac7d133d3aa752aae132b00c3ab79ee)
- スタッフの数が1以上
[![Image from Gyazo](https://i.gyazo.com/daf1f94b3c19513d74ece566e5559d3f.png)](https://gyazo.com/daf1f94b3c19513d74ece566e5559d3f)
- スタッフ0の状態でurl直接叩くと元の画面リダイレクト(遷移できない)
[loom動画](https://www.loom.com/share/57449e5651c64606b7160582d5b3878c)
- なし
```ruby
git fetch && git checkout origin/technical/restriction-thank-page
```
1. スタッフが存在するオフィスの詳細ページアクセス
- スタッフ一覧が表示されている
[![Image from Gyazo](https://i.gyazo.com/daf1f94b3c19513d74ece566e5559d3f.png)](https://gyazo.com/daf1f94b3c19513d74ece566e5559d3f)
- お礼投稿ページにアクセスできる
- url直うちでもアクセスできる
```ruby
thanks/new
```
2. スタッフが存在しないオフィスの詳細ページにアクセス
- スタッフ一覧が↓のように表示される …
> fix: スタッフが0だとお礼の投稿ボタン表示されない・直接url叩くと元のページにリダレクト

- .husky/pre-push
- pages/specialists/users/new.vue
- ケアマネ新規画面バリデーション修正
・名前：30文字以下
・パスワード：8文字以上32文字以下
・email：255文字以下
```ruby
git fetch && git checkout origin/fix/specialist_registration
```
1. 新規登録フォームでバリテーションがかかるか確認する
name 30文字超えるとエラー
email 255文字超えるとエラー
password 8文字より小さいエラー
password 32文字超えるとエラー
開発者ツールのコンソールで〇〇文字文用意
```ruby
'a'.repeat(255)
```
- なし
```javascript
NG
```
- …
> ケアマネ新規登録画面　バリデーション修正

- layouts/application_specialists.vue
- nuxt.config.js
- pages/specialists/login.vue
- pages/users/login.vue
- pages/users/new.vue
- plugins/validates.js
1. ログインフォームバリテーション設定
2. バリテーション共通関数化
- maxLength以外の共通関数化
```ruby
git fetch && git checkout origin/technical/login-validation
```
1. ケアマネログインフォーム、↓を検証
- email: 255文字以下
- password: 8文字以上32文字以下
2. カスタマーログインフォーム、↓を検証
- email: 255文字以下
- password: 8文字以上32文字以下
```ruby
'a'.repeat(255)
'a.'repeat(32)
```
- `plugins/validates.js`に移行したいルールを記述
```js
const maxLength = function () {
.
.
}
const hoge = function () {
.
.
}
export { maxLength, hoge }  // 作成した関数を追加
```
- バリテーション使いたい画面で読み込み `import { maxLength } from '@/plugins/validates'`
```html
<template>
<v-text-field
:rules="[
maxLength(form.email, 'メールーアドレス', 255),
hoge(**).
]"
>
</v-text-field>
</template>
<script>
import { maxLength, hoge } from '@/plugins/validates'  // 読見込み
export default {
.
.
methods: {
maxLength,  // 呼び出す …
```
> ケアマネ/カスタマー ログインフォームバリテーション修正

- components/ChooseCityCard.vue
1. エリアが選択されないバグの修正
- befoer
[loom動画 修正前](https://www.loom.com/share/dfe60d48afef4804b9edbfdef0858bc3)
- after
[loom動画 修正後](https://www.loom.com/share/6306b1cdd932451e9ab237151c3182e8)
- なし
```ruby
git fetch && git checkout origin/technical/office-left-menu
```
1. トップページからエリアを選択して検索する
2. 選択したエリアが一覧ページと一致する
3. トップページにもどって、1~2までを何度繰り返しても問題なければok  
※ 手順は↓と同じ
[loom動画 修正後](https://www.loom.com/share/6306b1cdd932451e9ab237151c3182e8)
- なし
```javascript
NG
```
```javascript
- アラート1
ログインをする必要があります
- アラート2
ログインをしてください …
```
> fix: オフィス検索エリア選択されないbug修正

- pages/offices/index.vue
- サーバーがdownしている時は遷移しないように設定
before
[![Image from Gyazo](https://i.gyazo.com/27f335eeaedbb2d02c5e4cf6729cc5ba.gif)](https://gyazo.com/27f335eeaedbb2d02c5e4cf6729cc5ba)
after
[![Image from Gyazo](https://i.gyazo.com/268c89cbd5e759ad2a2f6b4a4a3998fb.gif)](https://gyazo.com/268c89cbd5e759ad2a2f6b4a4a3998fb)
- なし
```ruby
git fetch && git checkout origin/technical/office-500-error-bug
```
1. api側のサーバーを停止する
2. トップページからリクエストする
3. 一覧ページへ遷移せずに、フラッシュメッセージが表示されることを確認する
[テスト仕様書](https://docs.google.com/spreadsheets/d/12xMuHo1K8Fd7FIB7rqeioxdWmrWw7aYK4QZ_Clsfk5Q/edit#gid …
> APIサーバーが起動していない時は、遷移しないように

- components/resetPasswords/new.vue
- nuxt.config.js
- pages/specialists/login.vue
- pages/users/login.vue
- pages/users/new.vue
- plugins/validates.js
- emailのフォーマット関係なく255文字超えるとエラー出るように修正
- components/resetPasswords/new.vue
- ### emailのフォーマットのバリテーションルールが優先されているため、255文字制限が評価されない
[![Image from Gyazo](https://i.gyazo.com/29f936c760323a3022e354572cdecf33.gif)](https://gyazo.com/29f936c760323a3022e354572cdecf33)
- ### emailのフォーマット突破するとようやくかかりだす
[![Image from Gyazo](https://i.gyazo.com/f6394e50ef31ff08ff6473784f1955db.gif)](https://gyazo.com/f6394e50ef31ff08ff6473784f1955db)
- ### 文字数が255文字超えたらフォーマット関係なくエラーが出る
[![Image from Gyazo](https://i.gyazo.com/15961177dc3fb5e0c58df219edca4c3c.gif)](https://gyazo.com/15961177dc3fb5e0c58df219edca4c3c)
- このプルリクでやらないことは何か？（**やらない場合は、いつやるのかを明記する**）
```ruby
git fetch && git checkout origin/technical/password-reset-validation
```
※ やったことのGIFのafterと同じか確認する
1. ケアマネパスワードリセット画面文字制限超えるとエラーでる …
> パスワードリセット画面文字数制限のバリテーション修正

- plugins/axios.js
- ステータスコードによってエラーメッセージ表示
- 401・403・422のステータスコードはAPIから返ってくるエラーメッセージを表示
- 認証系エラーとバリデーションエラーが該当します
- 500エラーはネットワークエラーとしてフロントで用意したエラーメッセージを表示（すでに用意済み）
- 上記に該当しないステータスコードが返ってきたときは、新たにフロントでメッセージを用意し、フラッシュメッセージに反映
- **障害が発生しました。サイト運営者にお問い合わせください。**
- なし
```ruby
git fetch && git checkout origin/technical/render_error_msg-customer_appointments_controller
```
```ruby
git fetch && git checkout origin/technical/switch-error-msg-for-api-status-code
```
- 予約作成画面に遷移する
- 名前・お困りごとを空白文字（半角・全角スペース）で入力する
- 確認画面に行き、予約ボタンを押す
- エラーメッセージが表示される
- APIでステータスコードを変えてみる
- `app/controllers/api/customer/appointments_controller.rb` の19行目の`status: ~~`を変更
before
```ruby
render status: :unprocessable_entity, json: { errors: appointment.errors.full_messages }
```
after
```ruby
render …
```
> ステータスコードによってエラーメッセージ表示

- components/appointment/officeCard.vue
- 予約一覧画面の画像表示部分の条件分岐修正
- 画像がないときはnullが返ってきたものを、空の配列を返すようにしたため
- なし
```ruby
git fetch && git checkout origin/fix/refactoring-bookmark-controller
```
```ruby
git fetch && git checkout origin/fix/appointments-index-display-img
```
- 予約一覧画面に遷移し、画像の表示が問題なくできるか確認する
- 画像なしオフィス、画像ありオフィス
- APIのプルリクこちら
https://github.com/koki-takishita/home-care-navi-api/pull/156
- なし
```javascript
NG
```
```javascript
- アラート1
ログインをする必要があります
- アラート2
ログインをしてください
- メールを送りました
OK
- メールを送信しました …
```
> 予約一覧画面の画像表示部分の条件分岐修正

- middleware/authenticateSpecialist.js
- ケアマネがログインしなくてもフッターのリンクにアクセスできるよう修正
- ログイン画面でログアウト処理が走る不具合の修正
```ruby
git fetch && git checkout origin/fix/specialist_login_to
```
ログインしていない状態で下記にアクセスする
- プライバシーポリシー
`http://localhost:8000/specialists/privacy_policy`
- 利用規約
`http://localhost:8000/specialists/terms`
- 問い合わせ
`http://localhost:8000/specialists/terms`
ケアマネとカスタマーのログイン画面を行き来してコンソールでエラーがないことを確認する
なし
```javascript
NG
```
```javascript
- アラート1
ログインをする必要があります
- アラート2
ログインをしてください
- メールを送りました
OK
- メールを送信しました …
```
> ログインしなくても遷移できる画面の追加

- pages/specialists/office/care-recipients/_care_recipient_id/edit.vue
- pages/specialists/office/care-recipients/new.vue
- pages/specialists/office/new.vue
- pages/specialists/office/staffs/_staff_id/edit.vue
- pages/specialists/office/staffs/new.vue
- svgの画像を登録したときに、画像が表示されないバグ修正
- 画像の拡張子が多すぎて管理しきれなく、今後もこういうバグが出てきそうなので、拡張子を制限しました。
- アップロードする画像の拡張子を制限（PNG, JPEG, JPG, GIFのみ）
- なし
```ruby
git fetch && git checkout origin/technical/add-image-upload-permission-extension
```
- スタッフや利用者などを登録・編集するときに、指定された拡張子以外の画像が選択できないか確認
- svgサンプル画像
- なし
```javascript
NG
```
```javascript
- アラート1
ログインをする必要があります
- アラート2
ログインをしてください
- メールを送りました
OK
- メールを送信しました
```
> アップロードする画像の拡張子を制限

- pages/offices/index.vue
- pages/top.vue
- plugins/axios.js
- plugins/officeSearch/conversionKeywords.js
- オフィス検索異常系の修正
- このプルリクでやらないことは何か？（**やらない場合は、いつやるのかを明記する**）
```ruby
git fetch && git checkout origin/technical/office-area-bug
```
- 一覧ページ
- 検索窓
1. 空の状態で検索
2. 空白の状態で検索
3. 存在しない検索ワード(オフィス名、住所、郵便番号)
4. 存在しない検索ワード(cの複数組み合わせ)
5. apiサーバー落とした状態で検索
[loom動画](https://www.loom.com/share/d57c2181615e425497fa7c5383496d4c)
- エリア選択パネル
1. city未選択の状態で検索
2. 存在しない地域で検索
3. apiサーバー落とした状態で検索
[loom動画](https://www.loom.com/share/6ab8abad847847a8ac9f0071fcbd2b5d)
- トップページ
- 検索窓
一覧ページと同じ項目
[loom動画](https://www.loom.com/share/a75cc46c51634c328ccae39b94cc3867)
- エリア選択パネル
一覧ページと同じ項目
[loom動画](https://www.loom.com/share/926f5f1dc55243df972cbd01b4966f50)
- 現在地
1. apiサーバー落とした状態
2. 現在地のデータ(新潟県・佐渡市)のデータ消した状態でリクエスト
[loom動画](https://www.loom.com/share/e0da9dc6395442dd8a4c55d1affbc9f6) …
> オフィス検索異常系のバグ修正

- pages/specialists/office/new.vue
- 事業所登録：入力フォーム上での空白NG（バリデーション設定）
　①空白だけでの入力をNG
　②『空白＋テキスト』の入力の場合、空白を自動削除する。
例：『□□□こんにちは』⇨『こんにちは』
[動作確認のGIF画面](https://gyazo.com/742b89b2139858bd7931f65fabc19475)
- API側での空白バリデーション設定
```ruby
git fetch && git checkout origin/technical/office-valid-message
```
- 事業所登録画面で確認する
```ruby
http://localhost:8000/specialists/office/new
```
以下の場面でバリデーションや空白の自動削除が掛かるか
①空白のみで入力してみる
②空白＋テキストを入力してみる
- [【v-model.trim】修飾子について](https://qiita.com/Yudai_35_/items/7e32d8f90e6d6f04e803)
- [半角スペースだけの文字列に合致する正規表現](https://qiita.com/kondo0602/items/2721eb77089c3de19406)
- [入力された文字列に含まれる空白文字を削除する方法](https://www.nishishi.com/javascript-tips/trim-space-chars.html) …
> 事業所登録：空白NG用valid

- pages/specialists/office/care-recipients/index.vue
- スタッフがいない時に利用者を追加できないように設定
- URL直打ち対策はしてないです
```ruby
git fetch && git checkout origin/fix/care-recipient_to
```
- スタッフがいない状態で利用者を登録しようとする
```ruby
手順1.ケアマネでログイン
手順2.ログインしたケアマネのオフィスに紐ずくスタッフを全削除
手順3.利用者を登録しようとする
手順4.アラート出る
手順5.スタッフ作る
手順6.利用者追加できる
```
[確認動画](https://www.loom.com/share/1763ccf182a446929094a84535b83565)
- なし
```javascript
NG
```
```javascript
- アラート1
ログインをする必要があります
- アラート2
ログインをしてください
- メールを送りました
OK
- メールを送信しました
```
> スタッフいないとき利用者登録遷移できないよう設定

- pages/specialists/office/care-recipients/_care_recipient_id/edit.vue
- pages/specialists/office/care-recipients/new.vue
- pages/specialists/office/new.vue
- pages/specialists/office/staffs/_staff_id/edit.vue
- pages/specialists/office/staffs/new.vue
- 10MBを超える画像を登録させないバリデーションを設定していたが、10MBピッタリの画像がアップロードできなかったので、正しいものに設定
- 10MBをバイトに変換すると`10,485,760`であるため、バイト数が`10,485,761`以上のものをアップロードするとバリデーションがかかるように修正
- なし
```ruby
git fetch && git checkout origin/fix/image-validation
```
- 事業所、スタッフ、利用者で画像アップロードを試す
- 10MBピッタリの画像はアップロードできる
- 10MBを超えるものはアップロードできない
[こちらのサイトのsample_5184×3456.pngをダウンロードしてください（34.24MB）](https://filesamples.com/formats/png)
- [バイト換算表](https://pasomaki.com/pc-byte-conversion/)
```javascript
NG
```
- …
> 画像バリデーション バイトサイズ正しいものに変更

- layouts/application_specialists.vue
- pages/specialists/users/new.vue
- pages/users/new.vue
- plugins/axios.js
- store/index.js
- オフィスがないケアマネ、左上アイコンクリックするとホワイト・アウトするバグ修正
- なし
```ruby
git fetch && git checkout origin/technical/move-top-page-to-specialist
```
- ケアマネのデータ用意する
- officeを持ってないユーザ
- office持っているユーザ
1. ケアマネログインする(office持ってない)
2. ログイン成功後、アイコンクリックするとofficeの新規作成画面ヘ遷移(画面上では変化なし)
1. ケアマネログインする(office持っている)
2. ログイン成功後、アイコンクリック予約状況画面へ遷移
- なし
```javascript
NG
```
```javascript
- アラート1
ログインをする必要があります
- アラート2
ログインをしてください
- メールを送りました
OK
- メールを送信しました
```
> ケアマネ側、ログイン後のアイコンクリック時の遷移先設定

- components/office/officeCard.vue
- officeカード、詳細とお礼が正しく表示されていなかった箇所修正
- before
[![Image from Gyazo](https://i.gyazo.com/75bd6e41a7784833ff8f1866f89807d3.png)](https://gyazo.com/75bd6e41a7784833ff8f1866f89807d3)
- after
- お礼が表示されてる　詳細登録されてないとされてないというmsgが表示されている
[![Image from Gyazo](https://i.gyazo.com/67e75945246e1676d04ff78a447430fe.png)](https://gyazo.com/67e75945246e1676d04ff78a447430fe)
- 詳細表示されている お礼がないと表示されてないというmsgが表示されている
[![Image from Gyazo](https://i.gyazo.com/82083c323567502eaa6320e036db6dd8.png)](https://gyazo.com/82083c323567502eaa6320e036db6dd8)
- このプルリクでやらないことは何か？（**やらない場合は、いつやるのかを明記する**）
```ruby
git fetch && git checkout origin/technical/office-component-bug
```
- 詳細を登録しているオフィスを検索する(ないなら作成する 項目はdetailのみでok) 
- 画像のように、お礼と詳細の項目が表示されている
[![Image from …
> officeカード お礼と詳細が正しく表示されるように修正

- pages/reset-passwords/edit.vue
- pages/reset-passwords/index.vue
- plugins/axios.js
- 404対応
- エンドポイントの共通化の対応
- なし
```ruby
git fetch && git checkout origin/technical/password-reset-query-set
```
```ruby
git fetch && git checkout origin/technical/password-reset-404
```
- フロントの`.envファイル`の`PASSWORD_RESET_REDIRECT_URL`を下記のように書き換え
```ruby
PASSWORD_RESET_REDIRECT_URL='https://home-care-navi-v2.herokuapp.com/reset-passwords/edit'
```
- フロントサーバー立ち上げなおし
- パスワードリセットを行う
- メールのリンクをクリックして遷移した画面のulrに必須のqueryがついていることを確認する(client, access-token, expiry, uid) ↓のようなqueryがついていればok
```ruby
https://home-care-navi-v2.herokuapp.com/reset-passwords/edit?type=customer&access-token=VMo7si4BVT0XveN7Nh_tKw&client=W0GKL4jB5R7LZsQhd2GR_Q&client_id=W0GKL4jB5R7LZsQhd2GR_Q&config=default&expiry=1663041249&reset_password=true&token=VMo7si4BVT0XveN7Nh_tKw&uid=mawatar …
```
> apiのエンドポイント共通化・404対応

- layouts/application.vue
- SP版トップページ ロゴクリックしてもトップに遷移しないバグ修正
- なし
```ruby
git fetch && git checkout origin/technical/set_action-sp_top_page_logo_click
```
- カスタマーでログインする
- トップページの画面サイズをスマホサイズ（**iphoneSE 375 x 667**）
- ヘッダーから閲覧履歴などに飛ぶ
- 左上のロゴをクリック
- トップに遷移すれば ✅ 
- なし
```javascript
NG
```
```javascript
- アラート1
ログインをする必要があります
- アラート2
ログインをしてください
- メールを送りました
OK
- メールを送信しました
```
> SP版トップページ ロゴクリックしてもトップに遷移しないバグ修正

- pages/specialists/office/new.vue
- pages/specialists/users/new.vue
- pages/users/new.vue
＜バグ改修＞
- 事業所登録ページ：（画像orテキスト）片方入力あるなら、片方も必須になる
　●エラーメッセージの表示
　●バリデーション（送信ボタンのON / OFF）
- typo一部修正
なし
```ruby
git fetch && git checkout origin/technical/office-image-valids
```
- 事業所登録フォームでバリデーションの設定確認
- 必須項目に入力してから、以下の項目を確認する。
　特徴画像① / 特徴画像①の説明文
　特徴画像② / 特徴画像②の説明文
エラー条件
```ruby
『特徴画像１』を入れた時、『特徴画像１の説明』が空
　登録できない→　エラー：特徴画像１を登録する場合、特徴画像1の説明は必須となります
『特徴画像１の説明』を入れた時、『特徴画像１』が空
　登録できない→　エラー：特徴画像1の説明を登録する場合、特徴画像１は必須となります
〜〜〜
特徴画像２ / 特徴画像２の説明も同様の条件
〜〜〜
```
メッセージ表示 と 送信ボタンON / OFF を確認する。
- [Vuetify: custom validator check failed for prop "value"](https://qiita.com/Sicut_study/items/ed41eb541cb6a8eef410)
- [vuetify の v-input-file …
> バグ改修：連動validメッセージ表示
